name: Builds

on:
  push:
  pull_request:
    branches:
      - master
      - 'release/**'

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  # linux:
  #   runs-on: ubuntu-latest
  #   env: {}
  #   steps:
  #     - uses: actions/checkout@v2

  macos:
    runs-on: macos-10.15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: >
          brew install ninja
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          additionalCachedPaths: ${{ github.workspace }}/build/vcpkg_installed
      - name: Configure
        run: >
          cmake -B build -S $PWD -GNinja 
      - name: Build
        working-directory: build
        run: >
          ninja
