name: Builds

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  job:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        if: ${{ contains("macos", matrix.os) }}
        run: brew install ninja
      - name: Install dependencies
        if: ${{ contains("windows", matrix.os) }}
        run: choco install ninja
      - name: Install dependencies
        if: ${{ contains("ubuntu", matrix.os) }}
        run: apt-get install -y ninja xinerama xcursor xorg libglu1-mesa

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          additionalCachedPaths: ${{ github.workspace }}/build/vcpkg_installed
      - name: Configure
        run: >
          cmake -B build -S $PWD
      - name: Build
        run: >
          cmake --build build
