name: Builds

on:
  push:
  pull_request:
    branches:
      - master
      - 'release/**'

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  # linux:
  #   runs-on: ubuntu-latest
  #   env: {}
  #   steps:
  #     - uses: actions/checkout@v2

  macos:
    runs-on: macos-10.15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            /Users/runner/.cache/vcpkg/archives/
          key: ${{ runner.os }}
      # - name: Install dependencies
        # run: >
          # vcpkg install glfw3 
      - name: Configure
        run: >
          cmake --version
          && mkdir build 
          && cmake -B build -S $PWD
              -GNinja 
              -DVCPKG_TARGET_TRIPLET=x64-osx
      - name:
        working-directory: build
        run: >
          ninja
